"use client";

import QRCode from "qrcode";
import { useEffect, useState } from "react";
import { MOCK_VALID_TOKEN } from "@/lib/mock";

/**
 * /dev/qr - DEMO TOOL, NOT PART OF THE PRODUCT.
 *
 * Renders the office poster the way it would be printed, so the scan flow can
 * be demonstrated end to end without a backend: display this on a laptop, scan
 * it with a phone, and the phone lands on /scan with the token in the URL.
 *
 * In the real system the admin dashboard draws this image from the scan_url the
 * backend stores. This page exists only so the staff app can be shown working
 * before that dashboard exists. Delete it once the dashboard does.
 *
 * The URL is built from window.location.origin rather than hardcoded, so the
 * same page produces a scannable code on localhost, on the LAN over https, and
 * on a deployed URL, with nothing to edit between them.
 */
export default function DevQrPage() {
  // Held as one object so the effect sets state once, in the promise callback,
  // rather than synchronously in its own body.
  const [poster, setPoster] = useState<{ url: string; image: string } | null>(null);

  useEffect(() => {
    const url = `${window.location.origin}/scan?t=${MOCK_VALID_TOKEN}`;
    let active = true;

    QRCode.toDataURL(url, {
      width: 880,
      margin: 1,
      // High correction so the code still reads off a laptop screen at an
      // angle, which is how it will be scanned during a demo.
      errorCorrectionLevel: "H",
      color: { dark: "#0d3b24", light: "#ffffff" },
    }).then((image) => {
      if (active) setPoster({ url, image });
    });

    return () => {
      active = false;
    };
  }, []);

  return (
    <main className="mx-auto flex min-h-full w-full max-w-xl flex-col items-center gap-6 px-6 py-10 text-center">
      <div className="flex flex-col gap-1">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">
          National Youth Service Corps
        </p>
        <h1 className="text-2xl font-bold text-foreground">Staff Attendance</h1>
        <p className="text-sm text-muted-foreground">NYSC FCT Secretariat</p>
      </div>

      <div className="rounded-2xl border-4 border-primary/20 bg-white p-4">
        {poster ? (
          // next/image cannot optimise a data URI generated in the browser, and
          // routing it through the image loader would only add a round trip.
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={poster.image}
            alt="Attendance QR code for NYSC FCT Secretariat"
            className="size-64 sm:size-72"
          />
        ) : (
          <div className="size-64 animate-pulse rounded bg-muted sm:size-72" />
        )}
      </div>

      <ol className="flex flex-col gap-2 text-sm text-muted-foreground">
        <li>1. Open the camera on your registered phone.</li>
        <li>2. Point it at this code.</li>
        <li>3. Tap the link, then tap Sign in.</li>
      </ol>

      <p className="mt-2 break-all rounded-md bg-muted px-3 py-2 font-mono text-xs text-muted-foreground">
        {poster?.url ?? "Loading..."}
      </p>

      <p className="text-xs text-muted-foreground">
        Demo tool. The real poster is generated by the admin dashboard.
      </p>
    </main>
  );
}
